/* worthly-data.jsx — Sample products & analyses for the Worthly prototype.
   Lives on window.WORTHLY so all other scripts can read it. */

const _WORTHLY_PRODUCTS = {
  "mx-master-3s": {
    id: "mx-master-3s",
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    category: "Wireless productivity mouse",
    image_tone: "#383532",
    image_accent: "#C8B68A",
    estimated_price: { low: 80, mid: 99, high: 110, currency: "USD" },
    current_offer: { price: 89, retailer: "B&H", delta_pct: -10 },
    verdict: "wait",
    score: 78,
    summary:
      "It's a great mouse — easily one of the best for productivity. But I'd hold off for two weeks: the new MX Master 4 is rumored at Logi's Sept event, which usually means a price drop on the 3S.",
    advisor_tldr: "I'd wait ~2 weeks.",
    reasons_for: [
      "Best-in-class ergonomics and silent click",
      "Excellent for multi-device workflows",
      "Long battery (~70 days) and USB-C",
    ],
    reasons_against: [
      "New model rumored within weeks",
      "Heavy at 141g — not for gaming",
      "Software still a bit clunky on macOS",
    ],
    price_history: [
      { m: "Jan", v: 99 }, { m: "Feb", v: 99 }, { m: "Mar", v: 95 },
      { m: "Apr", v: 99 }, { m: "May", v: 89 }, { m: "Jun", v: 99 },
      { m: "Jul", v: 92 }, { m: "Aug", v: 89 },
    ],
    similar: [
      {
        id: "mx-master-2s",
        name: "Logitech MX Master 2S",
        relation: "Older sibling",
        price: 59,
        score: 71,
        delta: "−$30",
        note: "Same shape, micro-USB, fewer buttons. Still excellent.",
      },
      {
        id: "razer-pro-click",
        name: "Razer Pro Click",
        relation: "Closest rival",
        price: 79,
        score: 68,
        delta: "−$10",
        note: "Better grip for big hands. Worse software.",
      },
      {
        id: "mx-anywhere-3s",
        name: "Logitech MX Anywhere 3S",
        relation: "Compact alt",
        price: 79,
        score: 74,
        delta: "−$10",
        note: "Travel-sized. Same scroll wheel, fewer buttons.",
      },
    ],
    reviews: {
      rating: 4.6,
      count: 18432,
      breakdown: { pros: 86, mixed: 9, cons: 5 },
      top_pros: [
        { tag: "Comfort", count: 4120, quote: "All-day comfort, no wrist fatigue." },
        { tag: "Silent clicks", count: 3204, quote: "You really can't hear them." },
        { tag: "Scroll wheel", count: 2890, quote: "MagSpeed scroll is unmatched." },
      ],
      top_cons: [
        { tag: "Weight", count: 1180, quote: "Heavier than I expected." },
        { tag: "Logi Options+", count: 982, quote: "Software crashes on macOS Sequoia." },
      ],
      sources: ["The Verge", "Wirecutter", "Rtings", "r/MouseReview"],
    },
    offers: [
      { retailer: "B&H Photo", price: 89, shipping: "Free", in_stock: true, badge: "Best price" },
      { retailer: "Amazon", price: 94, shipping: "Prime", in_stock: true, badge: null },
      { retailer: "Best Buy", price: 99, shipping: "Free", in_stock: true, badge: null },
      { retailer: "Logitech.com", price: 99, shipping: "$5", in_stock: true, badge: "Authentic" },
      { retailer: "Newegg", price: 96, shipping: "Free", in_stock: false, badge: null },
    ],
    fair_price: { low: 75, fair: 89, expensive: 105 },
  },
  "wh-1000xm5": {
    id: "wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "Over-ear noise-cancelling headphones",
    image_tone: "#1A1A1E",
    image_accent: "#7B8896",
    estimated_price: { low: 299, mid: 349, high: 399, currency: "USD" },
    current_offer: { price: 328, retailer: "Amazon", delta_pct: -6 },
    verdict: "buy",
    score: 91,
    summary:
      "Great call. The XM5 is at a near-historic low this week, and the XM6 isn't expected until early next year. Buy with confidence.",
    advisor_tldr: "Worth it — buy now.",
    reasons_for: [
      "Class-leading ANC, especially for voices",
      "$21 below 90-day average price",
      "Excellent battery (~30h) and quick charge",
    ],
    reasons_against: [
      "Non-folding design is awkward to travel with",
      "Calls slightly behind AirPods Max",
    ],
    price_history: [],
    similar: [],
    reviews: { rating: 4.7, count: 24112, breakdown: { pros: 89, mixed: 7, cons: 4 }, top_pros: [], top_cons: [], sources: [] },
    offers: [],
    fair_price: { low: 299, fair: 349, expensive: 399 },
  },
  "airpods-pro-2": {
    id: "airpods-pro-2",
    name: "AirPods Pro 2 (USB-C)",
    brand: "Apple",
    category: "Wireless earbuds",
    estimated_price: { low: 169, mid: 199, high: 249, currency: "USD" },
    current_offer: { price: 249, retailer: "Apple", delta_pct: 0 },
    verdict: "skip",
    score: 42,
    summary: "Honest take — the AirPods Pro 3 was announced last week. Skip this and grab the 3 when it ships in 10 days. Better ANC, better fit, same price tier.",
    advisor_tldr: "Skip — Pro 3 lands in 10 days.",
  },
};

const _WORTHLY_HISTORY = [
  {
    id: "h1",
    product_id: "mx-master-3s",
    product_name: "Logitech MX Master 3S",
    input_type: "text",
    verdict: "wait",
    summary: "I'd hold off ~2 weeks — MX Master 4 likely soon.",
    when: "Today · 2:14 PM",
    relative: "Just now",
  },
  {
    id: "h2",
    product_id: "wh-1000xm5",
    product_name: "Sony WH-1000XM5",
    input_type: "image",
    verdict: "buy",
    summary: "Near-historic low. Buy with confidence.",
    when: "Yesterday · 7:42 PM",
    relative: "1d",
  },
  {
    id: "h3",
    product_id: "airpods-pro-2",
    product_name: "AirPods Pro 2 (USB-C)",
    input_type: "text",
    verdict: "skip",
    summary: "Pro 3 lands in 10 days — wait.",
    when: "May 11 · 10:08 AM",
    relative: "3d",
  },
  {
    id: "h4",
    product_id: "kindle",
    product_name: "Kindle Paperwhite (12th gen)",
    input_type: "image",
    verdict: "buy",
    summary: "Solid upgrade, on sale, no successor in sight.",
    when: "May 8",
    relative: "1w",
  },
  {
    id: "h5",
    product_id: "dyson",
    product_name: "Dyson V15 Detect",
    input_type: "text",
    verdict: "wait",
    summary: "Refurbished V15 hits $499 most Black Fridays.",
    when: "May 2",
    relative: "2w",
  },
];

const _WORTHLY_SUGGESTIONS = [
  "Is the Steam Deck OLED worth it in 2026?",
  "Should I get the Kindle Paperwhite or Scribe?",
  "iPhone 17 Pro vs keeping my 15 Pro",
  "Best espresso machine under $500",
];

const _WORTHLY_VERDICTS = {
  buy: {
    key: "buy",
    label: "Buy",
    long: "Worth it",
    color: "var(--w-buy)",
    soft: "var(--w-buy-soft)",
    dot: "var(--w-buy)",
    code: "BUY",
  },
  wait: {
    key: "wait",
    label: "Wait",
    long: "Hold off",
    color: "var(--w-wait)",
    soft: "var(--w-wait-soft)",
    dot: "var(--w-wait)",
    code: "WAIT",
  },
  skip: {
    key: "skip",
    label: "Skip",
    long: "Not worth it",
    color: "var(--w-skip)",
    soft: "var(--w-skip-soft)",
    dot: "var(--w-skip)",
    code: "SKIP",
  },
};

window.WORTHLY = {
  products: _WORTHLY_PRODUCTS,
  history: _WORTHLY_HISTORY,
  suggestions: _WORTHLY_SUGGESTIONS,
  verdicts: _WORTHLY_VERDICTS,
};
